<a href="https://colab.research.google.com/github/trvossler-max/Deep_Learning_Challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("/charity_data.csv")
application_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

application_df

      APPLICATION_TYPE       AFFILIATION  ...   ASK_AMT IS_SUCCESSFUL
0                  T10       Independent  ...      5000             1
1                   T3       Independent  ...    108590             1
2                   T5  CompanySponsored  ...      5000             0
3                   T3  CompanySponsored  ...      6692             1
4                   T3       Independent  ...    142590             1
...                ...               ...  ...       ...           ...
34294               T4       Independent  ...      5000             0
34295               T4  CompanySponsored  ...      5000             0
34296               T3  CompanySponsored  ...      5000             0
34297               T5       Independent  ...      5000             1
34298               T3       Independent  ...  36500179             0

[34299 rows x 10 columns]

In [3]:
# Determine the number of unique values in each column.
application_df.nunique(axis=0)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T15', 'T29', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2190        1
C1283        1
C1570        1
C1248        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x>1]
#application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts()> 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C0           3
C1260        3
C2710        3
C1234        2
C3200        2
C1256        2
C1267        2
C1246        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications = application_df['CLASSIFICATION'].value_counts().loc[lambda x : x < 778]
classifications_to_replace = dict(classifications)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
final_application = pd.get_dummies(application_df)

final_application

       STATUS   ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0           1      5000  ...                         1                         0
1           1    108590  ...                         1                         0
2           1      5000  ...                         1                         0
3           1      6692  ...                         1                         0
4           1    142590  ...                         1                         0
...       ...       ...  ...                       ...                       ...
34294       1      5000  ...                         1                         0
34295       1      5000  ...                         1                         0
34296       1      5000  ...                         1                         0
34297       1      5000  ...                         1                         0
34298       1  36500179  ...                         1                         0

[34299 rows x 44 columns]

In [10]:
# Split our preprocessed data into our features and target arrays
X = final_application.copy()
y = final_application["IS_SUCCESSFUL"].copy()
X = X.drop("IS_SUCCESSFUL", axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=13)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=21, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=21, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 21)                924
_________________________________________________________________
dense_1 (Dense)              (None, 21)                462
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 22
=================================================================
Total params: 1,408
Trainable params: 1,408
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=90)

Epoch 1/90
804/804 [==============================] - 2s 2ms/step - loss: 0.5889 - accuracy: 0.7078
Epoch 2/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7276
Epoch 3/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7283
Epoch 4/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7297
Epoch 5/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5514 - accuracy: 0.7308
Epoch 6/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7303
Epoch 7/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7320
Epoch 8/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7319
Epoch 9/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 10/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7321
Epoch 11/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 12/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7330
Epoch 13/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7331
Epoch 14/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7342
Epoch 15/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7334
Epoch 16/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7338
Epoch 17/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7338
Epoch 18/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7350
Epoch 19/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7353
Epoch 20/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7351
Epoch 21/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7340
Epoch 22/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 23/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7361
Epoch 24/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7338
Epoch 25/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7362
Epoch 26/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7353
Epoch 27/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7351
Epoch 28/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7344
Epoch 29/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 30/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7366
Epoch 31/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7360
Epoch 32/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7356
Epoch 33/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7368
Epoch 34/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7357
Epoch 35/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7353
Epoch 36/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7362
Epoch 37/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7360
Epoch 38/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 39/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7358
Epoch 40/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7362
Epoch 41/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7354
Epoch 42/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7364
Epoch 43/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7354
Epoch 44/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7363
Epoch 45/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7375
Epoch 46/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7366
Epoch 47/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7371
Epoch 48/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7365
Epoch 49/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7367
Epoch 50/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 51/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7378
Epoch 52/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7371
Epoch 53/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7377
Epoch 54/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7370
Epoch 55/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7367
Epoch 56/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7372
Epoch 57/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7381
Epoch 58/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 59/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 60/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 61/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7380
Epoch 62/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7369
Epoch 63/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7368
Epoch 64/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7372
Epoch 65/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7375
Epoch 66/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7375
Epoch 67/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 68/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7381
Epoch 69/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7381
Epoch 70/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7375
Epoch 71/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7384
Epoch 72/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7365
Epoch 73/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7387
Epoch 74/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7376
Epoch 75/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7383
Epoch 76/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7381
Epoch 77/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7377
Epoch 78/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7375
Epoch 79/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7384
Epoch 80/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7384
Epoch 81/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7385
Epoch 82/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7380
Epoch 83/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7374
Epoch 84/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7379
Epoch 85/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7373
Epoch 86/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7384
Epoch 87/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7379
Epoch 88/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 89/90
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 90/90
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7388

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5526 - accuracy: 0.7264
Loss: 0.552635133266449, Accuracy: 0.7264139652252197

In [16]:
# Export our model to HDF5 file
nn.save('nn_model1')

INFO:tensorflow:Assets written to: nn_model1/assets

**Optimization 1:** Changing activation and epoch parameters and reducing the neurons in the hidden layers. No change to features.

In [22]:
nn_model2 = tf.keras.models.Sequential()

# First hidden layer
nn_model2.add(tf.keras.layers.Dense(units=8, activation="sigmoid", input_dim=43))

# Second hidden layer
nn_model2.add(tf.keras.layers.Dense(units=6, activation="relu"))

# Output layer
nn_model2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 8)                 352
_________________________________________________________________
dense_8 (Dense)              (None, 6)                 54
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 7
=================================================================
Total params: 413
Trainable params: 413
Non-trainable params: 0
_________________________________________________________________

In [23]:
# Compile the model
nn_model2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [29]:
fit_model = nn_model2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7365
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7367
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7357
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7356
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7365
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7359
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7371
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7366
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7370
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7369
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7370
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7372
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7366
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7372
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7374
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7366
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7372
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7365
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7366
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7371
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7364
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7377
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7377
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7369
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7366
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7360
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7371
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7365
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7364
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7371
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7373
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7371
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7358
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7370
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7375
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7371
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7366
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7372
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7372
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7374
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7362
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7377
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7366
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7367

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5511 - accuracy: 0.7303
Loss: 0.5511220097541809, Accuracy: 0.7302623987197876

In [31]:
# Export our model to HDF5 file
nn_model2.save('nn_model2')

INFO:tensorflow:Assets written to: nn_model2/assets

**Optimization 2:** Adding another hidden layer and changing the number of neural nodes and output activation function to the model and setting epochs to 75. No change to features

In [17]:
nn_model3 = tf.keras.models.Sequential()

# First hidden layer
nn_model3.add(tf.keras.layers.Dense(units=20, activation="sigmoid", input_dim=43))

# Second hidden layer
nn_model3.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Third hidden layer
nn_model3.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Output layer
nn_model3.add(tf.keras.layers.Dense(units=1, activation="tanh"))

# Check the structure of the model
nn_model3.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 20)                880
_________________________________________________________________
dense_4 (Dense)              (None, 16)                336
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 136
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9
=================================================================
Total params: 1,361
Trainable params: 1,361
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn_model3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
fit_model = nn_model3.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 2s 2ms/step - loss: 1.7161 - accuracy: 0.5774
Epoch 2/75
804/804 [==============================] - 1s 2ms/step - loss: 0.6155 - accuracy: 0.6925
Epoch 3/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5839 - accuracy: 0.7102
Epoch 4/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5757 - accuracy: 0.7156
Epoch 5/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5709 - accuracy: 0.7191
Epoch 6/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5688 - accuracy: 0.7226
Epoch 7/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5666 - accuracy: 0.7257
Epoch 8/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5650 - accuracy: 0.7252
Epoch 9/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7245
Epoch 10/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7267
Epoch 11/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7283
Epoch 12/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7283
Epoch 13/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7279
Epoch 14/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5539 - accuracy: 0.7293
Epoch 15/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5528 - accuracy: 0.7316
Epoch 16/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5540 - accuracy: 0.7306
Epoch 17/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7298
Epoch 18/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5514 - accuracy: 0.7297
Epoch 19/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7310
Epoch 20/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7317
Epoch 21/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7305
Epoch 22/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7309
Epoch 23/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7307
Epoch 24/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5534 - accuracy: 0.7313
Epoch 25/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7313
Epoch 26/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7294
Epoch 27/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7285
Epoch 28/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7322
Epoch 29/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7337
Epoch 30/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7336
Epoch 31/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5472 - accuracy: 0.7332
Epoch 32/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7343
Epoch 33/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7339
Epoch 34/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7345
Epoch 35/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7334
Epoch 36/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7352
Epoch 37/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7336
Epoch 38/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7335
Epoch 39/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7351
Epoch 40/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7343
Epoch 41/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7350
Epoch 42/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7343
Epoch 43/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7338
Epoch 44/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7349
Epoch 45/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7350
Epoch 46/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7343
Epoch 47/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7352
Epoch 48/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7345
Epoch 49/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7351
Epoch 50/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7366
Epoch 51/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7354
Epoch 52/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7359
Epoch 53/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7355
Epoch 54/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7352
Epoch 55/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7355
Epoch 56/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7362
Epoch 57/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7365
Epoch 58/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7364
Epoch 59/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7365
Epoch 60/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7360
Epoch 61/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7368
Epoch 62/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7359
Epoch 63/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7357
Epoch 64/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7372
Epoch 65/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7362
Epoch 66/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7372
Epoch 67/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7361
Epoch 68/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7362
Epoch 69/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7353
Epoch 70/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7373
Epoch 71/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7377
Epoch 72/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7357
Epoch 73/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7359
Epoch 74/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7370
Epoch 75/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7369

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5544 - accuracy: 0.7286
Loss: 0.5543981194496155, Accuracy: 0.7286297082901001

In [21]:
# Export our model to HDF5 file
nn_model3.save('nn_model3')

INFO:tensorflow:Assets written to: nn_model3/assets