<a href="https://colab.research.google.com/github/trvossler-max/Deep_Learning_Challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("/charity_data.csv")
application_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

application_df

      APPLICATION_TYPE       AFFILIATION  ...   ASK_AMT IS_SUCCESSFUL
0                  T10       Independent  ...      5000             1
1                   T3       Independent  ...    108590             1
2                   T5  CompanySponsored  ...      5000             0
3                   T3  CompanySponsored  ...      6692             1
4                   T3       Independent  ...    142590             1
...                ...               ...  ...       ...           ...
34294               T4       Independent  ...      5000             0
34295               T4  CompanySponsored  ...      5000             0
34296               T3  CompanySponsored  ...      5000             0
34297               T5       Independent  ...      5000             1
34298               T3       Independent  ...  36500179             0

[34299 rows x 10 columns]

In [4]:
# Determine the number of unique values in each column.
application_df.nunique(axis=0)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T15', 'T29', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1580        1
C1283        1
C2190        1
C2561        1
C1728        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x>1]
#application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts()> 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C4100        6
C1720        6
C2400        6
C1257        5
C1600        5
C2710        3
C1260        3
C0           3
C1267        2
C1246        2
C3200        2
C1256        2
C1234        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications = application_df['CLASSIFICATION'].value_counts().loc[lambda x : x < 778]
classifications_to_replace = dict(classifications)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
final_application = pd.get_dummies(application_df)

final_application

       STATUS   ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0           1      5000  ...                         1                         0
1           1    108590  ...                         1                         0
2           1      5000  ...                         1                         0
3           1      6692  ...                         1                         0
4           1    142590  ...                         1                         0
...       ...       ...  ...                       ...                       ...
34294       1      5000  ...                         1                         0
34295       1      5000  ...                         1                         0
34296       1      5000  ...                         1                         0
34297       1      5000  ...                         1                         0
34298       1  36500179  ...                         1                         0

[34299 rows x 44 columns]

In [11]:
# Split our preprocessed data into our features and target arrays
X = final_application.copy()
y = final_application["IS_SUCCESSFUL"].copy()
X = X.drop("IS_SUCCESSFUL", axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=13)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 6)                 264
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 7
=================================================================
Total params: 313
Trainable params: 313
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 1ms/step - loss: 0.6213 - accuracy: 0.6783
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5691 - accuracy: 0.7201
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.7252
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.7272
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7277
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7284
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5547 - accuracy: 0.7285
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7288
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5536 - accuracy: 0.7287
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7289
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7289
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7297
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5511 - accuracy: 0.7302
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5513 - accuracy: 0.7301
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7308
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7308
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7307
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5500 - accuracy: 0.7303
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7313
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7314
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7300
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7309
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7311
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7313
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7312
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7318
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7324
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7329
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7321
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7324
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7330
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7318
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7333
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7334
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7329
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7328
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7329
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7333
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7333
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7321
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7327
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7329
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7326
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7336
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7329
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7330
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7331
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7336
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7336

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5531 - accuracy: 0.7286
Loss: 0.5531181693077087, Accuracy: 0.7286297082901001

In [21]:
# Export our model to HDF5 file
nn.save('nn_model1')

INFO:tensorflow:Assets written to: nn_model1/assets

**Optimization 1:** Changing activation and epoch parameters and increasing neurons in first layer. No change to features.

In [22]:
nn_model2 = tf.keras.models.Sequential()

# First hidden layer
nn_model2.add(tf.keras.layers.Dense(units=8, activation="sigmoid", input_dim=43))

# Second hidden layer
nn_model2.add(tf.keras.layers.Dense(units=6, activation="relu"))

# Output layer
nn_model2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 8)                 352
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 54
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 7
=================================================================
Total params: 413
Trainable params: 413
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn_model2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
fit_model = nn_model2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6185 - accuracy: 0.6798
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5718 - accuracy: 0.7205
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5674 - accuracy: 0.7233
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5634 - accuracy: 0.7262
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5599 - accuracy: 0.7277
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7291
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7296
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7298
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7297
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7305
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5518 - accuracy: 0.7315
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7307
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7317
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7309
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7318
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7320
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7321
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7322
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7320
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7333
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7320
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7331
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7336
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7333
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7335
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7330
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7328
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7332
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7337
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7336
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7332
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7332
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7338
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7340
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7336
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7346
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7344
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7337
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7339
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7351
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7350
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7345
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7344
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7339
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7348
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7343
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7350
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7354
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7355
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7352
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7355
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7352
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7351
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7355
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7362
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7356
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7364
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7358
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7358
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7348
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7358
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7355
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7361
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7362
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7365
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7361
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7361
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7360
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7347
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7360
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7363
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7359
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7354
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7363
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7359
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7360
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7361
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7362
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7367
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7356
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7358
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7360
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7367
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7364
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7365
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7368
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7363
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7357
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7363
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7357
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7362
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7358
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7367

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5505 - accuracy: 0.7305
Loss: 0.5504993200302124, Accuracy: 0.7304956316947937

In [28]:
# Export our model to HDF5 file
nn_model2.save('nn_model2')

WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
INFO:tensorflow:Assets written to: nn_model2/assets

**Optimization 2:** Adding another hidden layer and more neural nodes to the model and setting epochs to 75. No change to features

In [23]:
nn_model3 = tf.keras.models.Sequential()

# First hidden layer
nn_model3.add(tf.keras.layers.Dense(units=20, activation="sigmoid", input_dim=43))

# Second hidden layer
nn_model3.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Third hidden layer
nn_model3.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Output layer
nn_model3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model3.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 20)                880
_________________________________________________________________
dense_10 (Dense)             (None, 16)                336
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 136
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 9
=================================================================
Total params: 1,361
Trainable params: 1,361
Non-trainable params: 0
_________________________________________________________________

In [24]:
# Compile the model
nn_model3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [25]:
fit_model = nn_model3.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 2s 1ms/step - loss: 0.5860 - accuracy: 0.7102
Epoch 2/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5648 - accuracy: 0.7249
Epoch 3/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5603 - accuracy: 0.7281
Epoch 4/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7276
Epoch 5/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7295
Epoch 6/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5543 - accuracy: 0.7287
Epoch 7/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5536 - accuracy: 0.7292
Epoch 8/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7313
Epoch 9/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5522 - accuracy: 0.7312
Epoch 10/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7299
Epoch 11/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7310
Epoch 12/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5513 - accuracy: 0.7314
Epoch 13/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5500 - accuracy: 0.7317
Epoch 14/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7311
Epoch 15/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7317
Epoch 16/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7326
Epoch 17/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7317
Epoch 18/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7321
Epoch 19/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7332
Epoch 20/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7334
Epoch 21/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7328
Epoch 22/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7348
Epoch 23/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7338
Epoch 24/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7327
Epoch 25/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7334
Epoch 26/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7341
Epoch 27/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5465 - accuracy: 0.7326
Epoch 28/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7343
Epoch 29/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 30/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7332
Epoch 31/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7347
Epoch 32/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7350
Epoch 33/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7334
Epoch 34/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7355
Epoch 35/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7355
Epoch 36/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7344
Epoch 37/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7336
Epoch 38/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7348
Epoch 39/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7345
Epoch 40/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7356
Epoch 41/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7363
Epoch 42/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7355
Epoch 43/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 44/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7348
Epoch 45/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7358
Epoch 46/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7362
Epoch 47/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7347
Epoch 48/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7360
Epoch 49/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7357
Epoch 50/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7367
Epoch 51/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7369
Epoch 52/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7362
Epoch 53/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7367
Epoch 54/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7371
Epoch 55/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7361
Epoch 56/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7364
Epoch 57/75
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7371
Epoch 58/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7360
Epoch 59/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7373
Epoch 60/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7361
Epoch 61/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7376
Epoch 62/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7363
Epoch 63/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7380
Epoch 64/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7363
Epoch 65/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7371
Epoch 66/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7378
Epoch 67/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7376
Epoch 68/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7364
Epoch 69/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7371
Epoch 70/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7373
Epoch 71/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 72/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7383
Epoch 73/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7372
Epoch 74/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7381
Epoch 75/75
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7371

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5516 - accuracy: 0.7291
Loss: 0.5515967011451721, Accuracy: 0.7290962338447571

In [27]:
# Export our model to HDF5 file
nn_model3.save('nn_model3')

INFO:tensorflow:Assets written to: nn_model3/assets